"""Generate Section B coverage inventory from AMS HGAP Combined Checklist v6.2 XLSX.

Outputs:
- compliance/_ams-coverage-section-b.md   (markdown table per worksheet)
- compliance/_ams-coverage-section-b.json (structured for further processing)
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parents[1] / "compliance"
XLSX = ROOT / "_ams-checklist-v6.2.xlsx"
RULESET = ROOT / "usda-hgap-v1.json"
OVERLAY = ROOT / "usda-hgap-overlay-leafy-greens-v1.json"
OUT_MD = ROOT / "_ams-coverage-section-b.md"
OUT_JSON = ROOT / "_ams-coverage-section-b.json"

# Force UTF-8 stdout to avoid charmap errors on Windows.
sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]

ruleset = json.loads(RULESET.read_text(encoding="utf-8-sig"))
overlay = json.loads(OVERLAY.read_text(encoding="utf-8-sig"))
RULESET_REVISION = ruleset.get("ruleset_revision", "unknown")
OVERLAY_REVISION = overlay.get("ruleset_revision", "unknown")

ams_to_controls = defaultdict(list)  # ams_id -> [smartfarm control id]
for ctl in ruleset["controls"]:
    for ams_id in ctl.get("ams_ids", []) or []:
        ams_to_controls[ams_id].append(ctl["id"])

overlay_ams_to_controls = defaultdict(list)
for ctl in overlay.get("controls", []):
    for ams_id in ctl.get("ams_ids", []) or []:
        overlay_ams_to_controls[ams_id].append(ctl["id"])

wb = openpyxl.load_workbook(XLSX, data_only=True)

WORKSHEETS = [
    ("Checklist-General Questions", "GQ", "G"),
    ("Checklist-Field Ops", "FO", "F"),
]

def normalize(value):
    if value is None:
        return ""
    return str(value).strip()

def is_ams_id(req: str, prefix: str) -> bool:
    """A real AMS control row has Req like G-2.1 or F-1.1.a, not G-1 (section header)."""
    if not req:
        return False
    req = req.strip()
    if not req.startswith(prefix + "-"):
        return False
    body = req[len(prefix) + 1:]
    # Section header = single integer (e.g. G-1). Control row = at least one dot (e.g. G-1.2).
    return "." in body

inventory = {}

for sheet_name, _short, prefix in WORKSHEETS:
    ws = wb[sheet_name]
    rows = []
    for r in range(1, ws.max_row + 1):
        req = normalize(ws.cell(row=r, column=1).value)
        text = normalize(ws.cell(row=r, column=2).value)
        doc = normalize(ws.cell(row=r, column=3).value)  # "DOC" required marker
        man = normalize(ws.cell(row=r, column=4).value)  # "MAN" mandatory marker
        if not is_ams_id(req, prefix):
            continue
        # Disposition
        in_base = ams_to_controls.get(req, [])
        in_overlay = overlay_ams_to_controls.get(req, [])
        if in_base:
            disposition = "mapped"
            mapped_to = in_base
        elif in_overlay:
            disposition = f"overlay-leafy-greens-{OVERLAY_REVISION}"
            mapped_to = in_overlay
        else:
            disposition = "unmapped"
            mapped_to = []
        rows.append({
            "row": r,
            "ams_id": req,
            "text": text,
            "doc_required": doc,
            "mandatory_marker": man,
            "disposition": disposition,
            "mapped_to": mapped_to,
        })
    inventory[sheet_name] = rows

# Stats
print("=== AMS HGAP Combined Checklist v6.2 coverage stats ===\n")
total_unmapped = 0
total_mapped = 0
total_overlay = 0
unmapped_by_section = defaultdict(list)
for sheet, rows in inventory.items():
    mapped = sum(1 for r in rows if r["disposition"] == "mapped")
    unmapped = sum(1 for r in rows if r["disposition"] == "unmapped")
    overlaid = sum(1 for r in rows if r["disposition"] == "overlay-leafy-greens-0.1.0")
    total_mapped += mapped
    total_unmapped += unmapped
    total_overlay += overlaid
    print(f"{sheet}: {len(rows)} control rows | mapped={mapped} overlay={overlaid} unmapped={unmapped}")
    for r in rows:
        if r["disposition"] == "unmapped":
            section = r["ams_id"].split(".")[0]
            unmapped_by_section[(sheet, section)].append(r["ams_id"])
print(f"\nTOTAL: mapped={total_mapped} overlay={total_overlay} unmapped={total_unmapped}")
print("\nUnmapped by AMS section:")
for (sheet, section), ids in sorted(unmapped_by_section.items()):
    print(f"  {sheet} / {section}: {len(ids)} - {', '.join(ids)}")

# Write JSON
OUT_JSON.write_text(json.dumps(inventory, indent=2, ensure_ascii=False), encoding="utf-8")

# Write Markdown
md_lines = ["# AMS Combined Checklist v6.2 - Coverage Section B (auto-generated)\n"]
md_lines.append(f"Generated by `scripts/parse_ams_checklist.py` from "
                f"`compliance/_ams-checklist-v6.2.xlsx` and ruleset {RULESET_REVISION}.\n")
md_lines.append(f"\n**Totals:** mapped={total_mapped}, overlay-leafy-greens={total_overlay}, "
                f"unmapped={total_unmapped} (total control rows={total_mapped + total_overlay + total_unmapped})\n")

for sheet_name, rows in inventory.items():
    md_lines.append(f"\n## {sheet_name}\n")
    md_lines.append("| Row | AMS id | Disposition | SmartFarm control(s) | Requirement (truncated) |")
    md_lines.append("| --- | --- | --- | --- | --- |")
    for r in rows:
        text = r["text"].replace("|", "/").replace("\n", " ")
        if len(text) > 110:
            text = text[:107] + "..."
        controls = ", ".join(r["mapped_to"]) if r["mapped_to"] else "-"
        md_lines.append(f"| {r['row']} | {r['ams_id']} | {r['disposition']} | {controls} | {text} |")

OUT_MD.write_text("\n".join(md_lines), encoding="utf-8")
print(f"\nWrote {OUT_MD}")
print(f"Wrote {OUT_JSON}")
